void kinit_gui(void);
void kclearscreen(void);
void kprint(const char* str, unsigned color, volatile unsigned short* start_addr);
void kprint_int(int value, unsigned short color, volatile unsigned short* start_addr);
void kprint_spaces(int count, unsigned short color, volatile unsigned short* start_addr);
void kwriteapp(const char* text, int start_c, int sorindex1, int sorindex2, unsigned color);
unsigned char kscancode_to_ascii(unsigned char scancode);
void kinput(int vga_pos_start, char* buffer, int buffer_size, int shadow_mode);
void kinput2(int vga_pos_start, char* buffer, int buffer_size, int shadow_mode);
static inline unsigned char kinb(unsigned short port);
int strcmp(const char* s1, const char* s2);
void kpause(void);
void int_to_string(int num, char* buffer);
void string_to_int(const char* str, int* out_num);
static inline void koutb(unsigned short port, unsigned char data);
static inline unsigned short kinw(unsigned short port);
void ata_wait_for_ready(void);
int read_sectors(unsigned int lba, unsigned char count, unsigned char* buffer);
int fat_read_bpb(void);
unsigned int fat_calc_lba(unsigned short cluster);
unsigned short fat_read_fat_entry(unsigned short cluster);
int read_file(const char* filename, char* output_buffer, int buffer_size);
int strlen(const char* str);
int write_sectors(unsigned int lba, unsigned char count, unsigned char* buffer);
static inline void koutw(unsigned short port, unsigned short data);
unsigned short fat_find_free_cluster(void);
char toupper(char c);
int fat_create_file_entry(const char* filename, unsigned short start_cluster, unsigned int file_size);
int create_file(const char* filename, const char* content, int len);
void run_app(const char* filename);
void run_assembly_code(void* app_address);
int delete_file(const char* filename);
int file_exists(const char* filename);
int hex_char_to_int(char c);
int hex_to_byte(const char* str);
void kputchar(char character, unsigned color, volatile unsigned short* addr);